### PR TITLE
Credits Page

### LINKED ISSUE #21: Add a Credits page
- [x] Add a `Contributor` class to `data`
- [x] Add contributors to `Contributor.contributors`
- [x] Create a `ContibutorCard` widget
- [x] Create the `CreditsPage` page
- [x] Replace the `AboutDialog` in the drawer

### PR DESCRIPTION
**Pull request by Levi-Lesches**
Fixes #21 
Blocked by #40

### CODE REVIEW

**Review by DavidTarrab — DISMISSED** [review]
yes

**Comment by Levi-Lesches** [comment]
Okay that's my final commit on the layout. Now everyone upload your details to `lib/src/data/contributor.dart`

**Review by DavidTarrab — DISMISSED** [review]

**Review by BraydenKO — COMMENTED** [review]
Is it right to put '21 as Vovsha's gradYear? Can we just leave it empty?

**Comment by Levi-Lesches** [comment]
I was thinking <year he arrived at Ramaz> - <year he left Ramaz>, but I couldn't find the year he arrived. I'll blank it out though

**Comment by Levi-Lesches** [comment]
OK looking good

**Review by BraydenKO — DISMISSED** [review]

**Review by todesj — APPROVED** [review]

**Review by DavidTarrab — APPROVED** [review]

**Pull request merged**
